music_directory "/home/akshaybapat/Music"
playlist_directory "/home/akshaybapat/.local/share/mpd/playlists"
db_file "/home/akshaybapat/.local/share/mpd/database"
log_file "/home/akshaybapat/.local/state/mpd/mpd.log"
pid_file "/home/akshaybapat/.local/state/mpd/mpd.pid"
state_file "/home/akshaybapat/.local/state/mpd/state"
sticker_file "/home/akshaybapat/.local/share/mpd/sticker.sql"

bind_to_address "/home/akshaybapat/.local/state/mpd/socket"
bind_to_address "127.0.0.1"
port "6600"

auto_update "yes"
restore_paused "yes"
filesystem_charset "UTF-8"

input {
  plugin "curl"
}

audio_output {
  type "pipewire"
  name "PipeWire"
}

audio_output {
  type "fifo"
  name "Visualizer feed"
  path "/home/akshaybapat/.local/state/mpd/mpd.fifo"
  format "44100:16:2"
}
