# Background and foreground colors
background = #060c00
foreground = #ffce77

# Standard colors
palette = 0=#060c00
palette = 1=#a27666
palette = 2=#6d805b
palette = 3=#85855a
palette = 4=#8c84ac
palette = 5=#af859d
palette = 6=#74aa9d
palette = 7=#ffce77

# Bright colors
palette = 8=#5f625c
palette = 9=#cb9984
palette = 10=#77925e
palette = 11=#969459
palette = 12=#9b91c7
palette = 13=#c78faf
palette = 14=#71bdac
palette = 15=#a5a19b
