background            #060c00
foreground            #ffce77

# black
color0  #060c00
color8  #5f625c

# red
color1  #a27666
color9  #cb9984

# green
color2  #6d805b
color10 #77925e

# yellow
color3  #85855a
color11 #969459

# blue
color4  #8c84ac
color12 #9b91c7

# magenta
color5  #af859d
color13 #c78faf

#cyan
color6  #74aa9d
color14 #71bdac

#white
color7  #ffce77
color15 #a5a19b


